# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9a69460117797789606b402385dbc86e"
name = "product-pdf-app-1"
application_url = "https://product-pdf.vercel.app"
embedded = true
handle = "product-pdf-app-2"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "karan-working.myshopify.com"

[webhooks]
api_version = "2025-04"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_orders,"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://product-pdf.vercel.app/auth/callback",
  "https://product-pdf.vercel.app/auth/shopify/callback",
  "https://product-pdf.vercel.app/api/auth/callback"
]

[pos]
embedded = false
